export const brand = {
  legalName: "Metaphor Automation Consulting",
  displayName: "Metaphor Automation Consulting",
  shortName: "Metaphor",
  tagline: "Intelligent Systems. Automated Results.",
  description:
    "AI automation consulting, intelligent websites, lead capture, booking systems, and connected business operations for growing companies.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://metaphor.dev",
  colors: {
    ink: "#0D0D14",
    graphite: "#1F2229",
    violet: "#6C4CFF",
    violetLight: "#8A6BFF",
    violetDark: "#5634E8",
    lime: "#B7FF2A",
    limeLight: "#C8FF36",
    limeDark: "#8FD900",
    ivory: "#F7F6F2",
    white: "#FFFFFF",
  },
  logos: {
    horizontalDark: "/brand/logos/metaphor-horizontal-dark.svg",
    horizontalLight: "/brand/logos/metaphor-horizontal-light.svg",
    horizontalMonoDark: "/brand/logos/metaphor-horizontal-mono-dark.svg",
    horizontalMonoLight: "/brand/logos/metaphor-horizontal-mono-light.svg",
    stackedDark: "/brand/logos/metaphor-stacked-dark.svg",
    stackedLight: "/brand/logos/metaphor-stacked-light.svg",
    compactDark: "/brand/logos/metaphor-compact-dark.svg",
    compactLight: "/brand/logos/metaphor-compact-light.svg",
    wordmarkDark: "/brand/logos/metaphor-wordmark-dark.svg",
    wordmarkLight: "/brand/logos/metaphor-wordmark-light.svg",
    wordmarkMono: "/brand/logos/metaphor-wordmark-mono.svg",
    symbolColor: "/brand/logos/metaphor-symbol-color.svg",
    symbolDark: "/brand/logos/metaphor-symbol-dark.svg",
    symbolLight: "/brand/logos/metaphor-symbol-light.svg",
    symbolViolet: "/brand/logos/metaphor-symbol-violet.svg",
    symbolOutline: "/brand/logos/metaphor-symbol-outline.svg",
    symbolMicro: "/brand/logos/metaphor-symbol-micro.svg",
    monogram: "/brand/logos/metaphor-monogram.svg",
  },
  icons: {
    favicon: "/brand/favicons/favicon.ico",
    faviconSvg: "/brand/favicons/favicon.svg",
    appleTouch: "/brand/favicons/apple-touch-icon.png",
    safariPinnedTab: "/brand/favicons/safari-pinned-tab.svg",
    manifest: "/brand/favicons/site.webmanifest",
    app192: "/brand/app-icons/icon-192x192.png",
    app512: "/brand/app-icons/icon-512x512.png",
    app1024: "/brand/app-icons/icon-1024x1024.png",
    maskable192: "/brand/app-icons/maskable-192x192.png",
    maskable512: "/brand/app-icons/maskable-512x512.png",
    socialAvatar: "/brand/app-icons/social-avatar-512x512.png",
  },
} as const;

export type BrandLogoVariant = keyof typeof brand.logos;
